name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        npm install
        npm run build

    # Add the following steps to commit and push build folder
    - name: Commit and Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      run: |
        git config --global user.email "gli0471@hotmail.com"
        git config --global user.name "Alex"
        git add .
        git commit -m "Add npm build files"
        git push
